import Head from 'next/head'
import { getAllArticles, getArticleBySlug } from '../../../lib/data'
import { serialize } from 'next-mdx-remote/serialize'
import { MDXRemote } from 'next-mdx-remote'

export default function BlogPage ({ lang, title, date, content }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='border-t-2 p-4 border-black space-y-2'>
        <h1 className='text-red-700 text-3xl font-extrabold font-serif'>
          {title}
        </h1>
        <h6 className='text-gray-600'>{date}</h6>
        <p className='prose'>
          <MDXRemote {...content} />
        </p>
      </main>
    </div>
  )
}

export async function getStaticProps ({ params }) {
  const { data, content } = getArticleBySlug(params?.lang, params?.slug)
  return {
    props: {
      lang: data.lang,
      title: data.title,
      date: data.date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      }),
      content: await serialize(content)
    }
  }
}

export async function getStaticPaths () {
  const articles = getAllArticles()
  return {
    paths: articles.map(item => ({
      params: { lang: item.data.lang, slug: item.slug }
    })),
    fallback: false
  }
}
