import Head from 'next/head'
import { blogPosts } from '../../lib/data'

export default function BlogPage ({ title, date, content }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='border-t-2 p-4 border-black space-y-2'>
        <h1 className='text-red-700 text-3xl font-extrabold font-serif'>
          {title}
        </h1>
        <h6 className='text-gray-600'>{date}</h6>
        <p className='font-mono'>{content}</p>
      </main>
    </div>
  )
}

export async function getStaticProps (context) {
  console.log('context', context)
  return { props: blogPosts.find(item => item.slug === context.params.slug) }
}

export async function getStaticPaths () {
  return {
    paths: blogPosts.map(item => ({ params: { slug: item.slug } })),
    fallback: false
  }
}
