import Head from 'next/head'
import useTranslation from '../hooks/useTranslation'

export default function About () {
  const { translate } = useTranslation()
  return (
    <div>
      <Head>
        <title>{translate('about')}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='mt-7'>
        <h1 className='text-lg my-4'>{translate('about')}</h1>
        <p className='font-serif .leading-6 font-thin'>
          {translate('about-page')}
        </p>
      </main>
    </div>
  )
}
