import Head from 'next/head'
import useTranslation from '../hooks/useTranslation'

export default function About () {
  const { translate } = useTranslation()
  return (
    <div>
      <Head>
        <title>
          {translate('blogName')}: {translate('about')}
        </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>{translate('about')}</h1>
      </main>
    </div>
  )
}
