import { data } from 'autoprefixer'
import Head from 'next/head'
import Link from 'next/link'
import { getAllPosts } from '../lib/data'

export default function Home ({ posts }) {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <ul>
          {posts.map(item => (
            <BlogListItem key={item.slug} {...item} />
          ))}
        </ul>
      </main>
    </div>
  )
}

export async function getStaticProps () {
  const posts = getAllPosts()
  return {
    props: {
      posts: posts.map(({ data, content, slug }) => ({
        title: data.title,
        date: data.date.toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        }),
        content,
        slug
      }))
    }
  }
}

function BlogListItem ({ slug, title, date, content }) {
  return (
    <Link href={`/blog/${slug}`}>
      <li className='border-gray-200 border-2 rounded-md p-4 my-3 shadow hover:shadow-lg space-y-1 cursor-pointer'>
        <h5 className='text-xl text-blue-700'>{title}</h5>
        <div className='text-sm text-gray-600'>{date}</div>
        <p className='truncate'>{content}</p>
      </li>
    </Link>
  )
}
